config/routes.rb
Maplouis::Application.routes.draw do

  devise_for :users

  resources :businesses do
    collection do
      get "tagged/:tag" => "businesses#tagged", :as => :tagged
    end
  end

  root :to => "main#index"

end

app/models/business.rb
class Business < ActiveRecord::Base
  acts_as_taggable
  acts_as_gmappable :lat => 'lat', :lng => 'lng', 
                    :check_process => :prevent_geocoding,
                    :address => "address", :normalized_address => "address",
                    :msg => "Sorry, not even Google could figure out where that is"

  belongs_to :user

  validates_presence_of :name, :address, :description

  def prevent_geocoding
    address.blank? || (!lat.blank? && !lng.blank?) 
  end

  def gmaps4rails_infowindow
    "<h3>#{ self.name }</h3><div>#{self.address}</div><hr/ ><div>#{self.description}</div>"
  end
end
# == Schema Information
#
# Table name: businesses
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  address     :string(255)
#  description :text
#  website     :string(255)
#  twitter     :string(255)
#  email       :string(255)
#  approved    :boolean         default(FALSE)
#  lat         :string(255)
#  lng         :string(255)
#  gmaps       :boolean
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :businesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :tagged, :show]

  # GET /businesses
  def index
    @businesses = Business.order(:name)
  end

  def tagged
    @tag = params[:tag]
    @businesses = Business.tagged_with(@tag)
  end

  # GET /businesses/1
  def show
    @business = Business.find(params[:id])
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
    @business = current_user.businesses.find(params[:id])
  end

  # POST /businesses
  def create
    @business = current_user.businesses.build(params[:business])

    if @business.save
      redirect_to @business, notice: 'Business was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /businesses/1
  def update
    @business = current_user.businesses.find(params[:id])

    if @business.update_attributes(params[:business])
      redirect_to @business, notice: 'Business was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /businesses/1
  def destroy
    @business = current_user.businesses.find(params[:id])
    @business.destroy

    redirect_to root_url #businesses_url
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @businesses = Business.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_links(tags)
    tags.sort{|a,b|a.name <=> b.name}.collect {|t| link_to t.name, tagged_businesses_path(t.name)}.join(", ").html_safe
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation" class="alert-message block-message error">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% @business.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :name, "Business Name" %>
    <div class="input">
      <%= f.text_field :name, :class => "xxlarge" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :address, "Full Address" %>
    <div class="input">
      <%= f.text_field :address, :class => "xxlarge" %>
      <span class="help-block">Example: 2603 Cherokee Street, St Louis, MO</span>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :description %>
    <div class="input">
      <%= f.text_area :description, :class => "xxlarge", :rows => 4 %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :tag_list, "Tags" %>
    <div class="input">
      <%= f.text_field :tag_list, :class => "xxlarge" %>
      <span class="help-block">Example: Web Development, Web Design, Rails, Ruby</span>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :website %>
    <div class="input">
      <%= f.text_field :website, :class => "xxlarge" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :twitter, "Company Twitter" %>
    <div class="input">
      <div class="input-prepend">
        <span class="add-on">@</span>
        <%= f.text_field :twitter %>
      </div>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :email, "Company Email" %>
    <div class="input">
      <%= f.text_field :email %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn primary" %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<div class="page-header"><h1>Listing businesses</h1></div>

<div class="row">
  <div class="span16">
    <table id="businesses" class="zebra-striped">
      <tr>
        <th>Name</th>
        <th>Description</th>
      </tr>

      <% @businesses.each do |business| %>
        <tr>
          <td class="span3"><%= link_to business.name, business %></td>
          <td class="span13"><%= business.description %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<script type="text/javascript">
</script>

app/views/businesses/new.html.erb
<div class="page-header"><h1>Add Your Business</h1></div>
<div class="row">
  <div class="span4">
  </div>
  <div class="span12">
    <%= render 'form' %>
  </div>
</div>

app/views/businesses/show.html.erb
<div class="page-header"><h1><%= link_to @business.name, @business.website %></h1></div>

<div class="row">
  <div class="span10">
    <h4>About</h4>
    <p><%= @business.description %></p>
    <p>Tags: <%= tag_links @business.tags %></p>
  </div>
  <div class="span6">
    <h4>Contact Information</h4>
    <p><%= link_to "@#{@business.twitter}", "http://twitter.com/#{@business.twitter}" %></p>
    <p><%= mail_to @business.email %></p>
    <p><%= @business.address %></p>
  </div>

  <div class="span16 gmaps">
    <div class="page-header"><h3>Location</h3></div>
    <%= gmaps4rails Array(@business).to_gmaps4rails %>
  </div>

  <% if user_signed_in? and @business.user_id == current_user.id %>
    <div class="span16">
      <div class="well">
        <p>You are the owner of this page. Make sure to keep it up to date!</p>
        <%= link_to 'Edit This Page', edit_business_path(@business), :class => "btn primary" %>
        <%= link_to 'Delete This Page', edit_business_path(@business), :class => "btn danger", :method => :delete, :confirm => "Are you sure?" %>
      </div>
    </div>
  <% end %>

</div>

app/views/businesses/tagged.html.erb
<div class="page-header"><h1>Businesses Tagged With "<%= @tag %>"</h1></div>

<div class="row">
  <div class="span16">
    <table id="businesses" class="zebra-striped">
      <tr>
        <th>Name</th>
        <th>Description</th>
      </tr>

      <% @businesses.each do |business| %>
        <tr>
          <td class="span3"><%= link_to business.name, business %></td>
          <td class="span13"><%= business.description %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<script type="text/javascript">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maplouis</title>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "http://twitter.github.com/bootstrap/1.4.0/bootstrap.css", "application" %>
  <%= javascript_include_tag "application", "http://autobahn.tablesorter.com/jquery.tablesorter.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="topbar">
    <div class="fill">
      <div class="container">
        <a class="brand" href="<%= root_path %>">Start Louis Map</a>
        <ul class="nav">
          <li><%= link_to "Businesses", businesses_path %></li>
          <li><%= link_to "Add Yours", new_business_path %></li>
        </ul>
        <p class="pull-right" style="color:white">
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
          or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
        </p>
      </div>
    </div>
  </div>


  <div class="container">

    <% if notice %><div class="alert-message block-message info"><%= notice %></div><% end %>
    <% if alert %><div class="alert-message block-message error"><%= alert %></div><% end %>


    <%= yield %>

    <footer>
      <p class="pull-right"><small>Created by <%= link_to "Chris Oliver", "http://excid3.com" %></small></p>
      <p><small>Made in St. Louis, Missouri<small></p>
    </footer>
  </div>

  <%= yield :scripts %>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-8399719-12']);
    _gaq.push(['_trackPageview']);

    (function() {
     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

   </script>
</body>
</html>

app/views/main/index.html.erb
<div class="row">
  <div class="span16 gmaps">
    <%= gmaps4rails @businesses.to_gmaps4rails %>
  </div>
</div>

<div class="row">
  <% @businesses[0..3].each do |business| %>
    <div class="span4">
      <h2><%= link_to business.name, business %></h2>
      <p><%= business.description %></p>
      <p><%= link_to "View details", business, :class => "btn" %></p>
    </div>
  <% end %>
</div>